/**
 * Per-concept micro-checks for core concepts that were authored after the initial
 * lessons (ROADMAP M3). Kept in a separate module and merged onto the matching
 * concept at load (see concepts.ts) so the building-block checks live in one place.
 * Each item is tagged with the concept it tests and, where one fits, the
 * misconception it probes (METHODOLOGY §12).
 */
import type { QuizQuestion } from "../types";

export const EXTRA_MICROQUIZ: Record<string, QuizQuestion[]> = {
  string: [{
    id: "mq-string-1", type: "true-false",
    prompt: "“$\\forall + = ))0$” counts as a *string* over the alphabet.",
    correct: true,
    explanation: "A string is *any* finite sequence of symbols — legal or gibberish. Being a string says nothing about being well-formed.",
    concepts: ["string"],
  }],
  "formation-rule": [{
    id: "mq-formation-rule-1", type: "multiple-choice",
    prompt: "What does a formation rule do?",
    options: ["Decides whether a sentence is true", "Builds/declares which strings are well-formed expressions", "Derives theorems from axioms", "Assigns meaning to symbols"],
    correct: 1,
    explanation: "Formation rules are *grammar*: they say which strings are well-formed. Truth (semantics) and derivation (proof) are separate.",
    concepts: ["formation-rule"],
  }],
  "atomic-formula": [{
    id: "mq-atomic-formula-1", type: "multiple-choice",
    prompt: "Which is an atomic formula?",
    options: ["$\\forall x(x=x)$", "$2+2=4$", "$P \\wedge Q$", "$\\neg(0=1)$"],
    correct: 1,
    explanation: "An atomic formula is two terms joined by $=$ — no connectives or quantifiers. The others are built from atomic formulas.",
    concepts: ["atomic-formula"],
  }],
  quantifier: [{
    id: "mq-quantifier-1", type: "true-false",
    prompt: "In $\\forall x\\,(x+0=x)$, the $\\forall x$ binds $x$, turning an open formula into a closed one (a sentence).",
    correct: true,
    explanation: "A quantifier binds the variable it ranges over; binding every free variable yields a sentence with a definite truth value in a structure.",
    concepts: ["quantifier"],
  }],
  "inference-rule": [{
    id: "mq-inference-rule-1", type: "multiple-choice",
    prompt: "Modus ponens lets you write $Q$ once you have…",
    options: ["$Q$ is true in $\\mathbb{N}$", "$P$ and $P\\to Q$", "$\\neg Q \\to \\bot$", "a proof that $Q$ is an axiom"],
    correct: 1,
    explanation: "An inference rule is purely syntactic: from $P$ and $P\\to Q$, derive $Q$. No appeal to truth.",
    concepts: ["inference-rule"],
  }],
  "formal-theory": [{
    id: "mq-formal-theory-1", type: "multiple-choice",
    prompt: "A formal theory is…",
    options: ["the set of all true sentences", "a set of axioms plus inference rules for deriving statements", "a structure with a domain", "a decision procedure"],
    correct: 1,
    explanation: "A theory = axioms + inference rules (e.g. PA). Its *theorems* are what the rules derive — not, in general, all truths.",
    concepts: ["formal-theory"],
  }],
  provability: [{
    id: "mq-provability-1", type: "multiple-choice",
    prompt: "$T \\vdash P$ asserts that…",
    options: ["$P$ is true in $\\mathbb{N}$", "some finite derivation of $P$ from $T$ exists", "$P$ is an axiom of $T$", "$P$ is well-formed"],
    correct: 1,
    explanation: "Provability is the *existence* of a derivation — a syntactic, existential claim. It is not the same as truth ($\\models$).",
    concepts: ["provability"], misconceptions: ["true-prov"],
  }],
  interpretation: [{
    id: "mq-interpretation-1", type: "true-false",
    prompt: "An interpretation can send the symbol “$+$” to a function other than addition.",
    correct: true,
    explanation: "An interpretation freely assigns meanings to symbols; “$+$” denotes addition only under the *intended* interpretation. The symbol is not the function.",
    concepts: ["interpretation"],
  }],
  structure: [{
    id: "mq-structure-1", type: "multiple-choice",
    prompt: "A structure consists of…",
    options: ["axioms and inference rules", "a domain of objects + an interpretation of every symbol", "a set of theorems", "a proof of consistency"],
    correct: 1,
    explanation: "A structure = domain + interpretation. Satisfaction ($\\models$) is defined relative to a structure.",
    concepts: ["structure"],
  }],
  syntactic: [{
    id: "mq-syntactic-1", type: "multiple-choice",
    prompt: "Which is a *syntactic* notion?",
    options: ["truth in $\\mathbb{N}$", "$\\models$", "the turnstile $\\vdash$ (derivability)", "the domain of a structure"],
    correct: 2,
    explanation: "$\\vdash$ is syntactic — about symbol manipulation in derivations. $\\models$ and truth are semantic.",
    concepts: ["syntactic"], misconceptions: ["true-prov"],
  }],
  contradiction: [{
    id: "mq-contradiction-1", type: "true-false",
    prompt: "If $T \\vdash P$ and $T \\vdash \\neg P$ for some $P$, then $T$ is inconsistent.",
    correct: true,
    explanation: "Proving a sentence and its negation is a contradiction; equivalently $T$ then proves $0=1$.",
    concepts: ["contradiction"],
  }],
  completeness: [{
    id: "mq-completeness-1", type: "multiple-choice",
    prompt: "A *theory* $T$ is complete when…",
    options: ["$T$ proves only true sentences", "for every sentence $P$, $T\\vdash P$ or $T\\vdash\\neg P$", "$T$ is consistent", "every valid formula is provable (Gödel completeness)"],
    correct: 1,
    explanation: "Theory-completeness = every sentence is decided. That's distinct from *soundness* (only truths) and from the Completeness Theorem.",
    concepts: ["completeness"], misconceptions: ["sound-complete-same"],
  }],
  "object-theory": [{
    id: "mq-object-theory-1", type: "multiple-choice",
    prompt: "“PA proves $2+2=4$” is a statement of…",
    options: ["the object-theory (inside PA)", "the metatheory (about PA)", "neither", "both equally"],
    correct: 1,
    explanation: "Claims *about* what PA proves are metatheoretic. PA's own sentences are about numbers, not about PA.",
    concepts: ["object-theory"], misconceptions: ["obj-meta"],
  }],
  metatheory: [{
    id: "mq-metatheory-1", type: "true-false",
    prompt: "“$T$ is consistent” is a statement made in the *metatheory*, not inside $T$.",
    correct: true,
    explanation: "Consistency is a claim *about* $T$ — metatheoretic. (Its arithmetized proxy $\\mathrm{Con}(T)$ can be written inside $T$, but that's a different, encoded object.)",
    concepts: ["metatheory"], misconceptions: ["obj-meta"],
  }],
  "recursively-enumerable": [{
    id: "mq-recursively-enumerable-1", type: "multiple-choice",
    prompt: "A set is recursively enumerable when…",
    options: ["an algorithm decides membership and non-membership", "an algorithm can *list* its members (may run forever on non-members)", "it is finite", "it is primitive recursive"],
    correct: 1,
    explanation: "r.e. = listable / semi-decidable. Decidable is stronger (halts on members *and* non-members).",
    concepts: ["recursively-enumerable"], misconceptions: ["undecidable-slow"],
  }],
  "primitive-recursive": [{
    id: "mq-primitive-recursive-1", type: "true-false",
    prompt: "Checking whether $p$ codes a valid $T$-proof of $q$ is a primitive-recursive (always-halting) relation.",
    correct: true,
    explanation: "Proof-checking is mechanical and bounded — primitive recursive. (Proof-*finding* is not; that's where undecidability enters.)",
    concepts: ["primitive-recursive"],
  }],
  "effectively-axiomatized": [{
    id: "mq-effectively-axiomatized-1", type: "multiple-choice",
    prompt: "“Effectively axiomatized” means…",
    options: ["finitely many axioms", "the axioms can be mechanically listed (the axiom set is r.e.)", "all axioms are true", "the theory is complete"],
    correct: 1,
    explanation: "It's about *recognizability* of axioms, not finiteness — PA has infinitely many axioms (schemas) yet is effectively axiomatized.",
    concepts: ["effectively-axiomatized"],
  }],
  "godel-coding": [{
    id: "mq-godel-coding-1", type: "true-false",
    prompt: "Gödel coding makes the *number* $\\ulcorner P\\urcorner$ literally understand or assert $P$.",
    correct: false,
    explanation: "Coding only assigns numbers to syntax; the number doesn't 'mean' anything by itself. Self-reference is recovered by a *theorem* (the Fixed-Point Lemma), not by the number understanding itself.",
    concepts: ["godel-coding"], misconceptions: ["code-understands"],
  }],
  "code-number": [{
    id: "mq-code-number-1", type: "multiple-choice",
    prompt: "$\\ulcorner P\\urcorner$ denotes…",
    options: ["the truth value of $P$", "the natural number assigned to the syntactic object $P$", "a proof of $P$", "the negation of $P$"],
    correct: 1,
    explanation: "The corner brackets are the code-number: the natural number naming the syntactic object $P$.",
    concepts: ["code-number"],
  }],
  arithmetization: [{
    id: "mq-arithmetization-1", type: "multiple-choice",
    prompt: "Arithmetization re-expresses…",
    options: ["truth as provability", "syntactic relations (well-formedness, proof-hood) as arithmetic relations among code-numbers", "numbers as formulas", "PA as set theory"],
    correct: 1,
    explanation: "Arithmetization turns 'is a proof of' etc. into arithmetic relations on code-numbers — letting arithmetic talk about its own syntax.",
    concepts: ["arithmetization"],
  }],
  representable: [{
    id: "mq-representable-1", type: "multiple-choice",
    prompt: "A relation is *representable* in $T$ when…",
    options: ["it is true in $\\mathbb{N}$", "$T$ can *prove* the representing formula of exactly the right tuples (and refute it of the rest)", "it is decidable", "it is an axiom"],
    correct: 1,
    explanation: "Representability is a *proof-theoretic* property ($T\\vdash$ / $T\\vdash\\neg$), not mere truth in $\\mathbb{N}$ — keeping $\\vdash$ and $\\models$ apart.",
    concepts: ["representable"], misconceptions: ["true-prov"],
  }],
  "proof-predicate": [{
    id: "mq-proof-predicate-1", type: "true-false",
    prompt: "$\\mathrm{Proof}_T(p,q)$ ('$p$ codes a $T$-proof of the formula coded by $q$') is a decidable arithmetic relation.",
    correct: true,
    explanation: "Proof-checking is mechanical, so $\\mathrm{Proof}_T$ is decidable (primitive recursive) and arithmetically representable.",
    concepts: ["proof-predicate"],
  }],
  "prov-predicate": [{
    id: "mq-prov-predicate-1", type: "multiple-choice",
    prompt: "$\\mathrm{Prov}_T(q) \\equiv \\exists p\\,\\mathrm{Proof}_T(p,q)$ is…",
    options: ["decidable, like $\\mathrm{Proof}_T$", "only *recursively enumerable* (the existential quantifier searches unboundedly)", "always false", "the same as truth in $\\mathbb{N}$"],
    correct: 1,
    explanation: "Adding the unbounded $\\exists p$ makes provability r.e., not decidable — you can confirm a proof exists by finding it, but can't always confirm none does.",
    concepts: ["prov-predicate"],
  }],
  diagonalization: [{
    id: "mq-diagonalization-1", type: "true-false",
    prompt: "The self-reference in Gödel's construction is achieved by a theorem (the Fixed-Point Lemma) via coding, not by a sentence literally containing itself.",
    correct: true,
    explanation: "Diagonalization produces a sentence *provably equivalent* to a claim about its own code-number — mechanical, not the English liar's direct self-reference.",
    concepts: ["diagonalization"], misconceptions: ["liar"],
  }],
  "fixed-point-lemma": [{
    id: "mq-fixed-point-lemma-1", type: "multiple-choice",
    prompt: "The Fixed-Point Lemma guarantees, for a formula $\\psi(x)$, a sentence $G$ with…",
    options: ["$G$ is true iff $\\psi$ is true", "$T \\vdash G \\leftrightarrow \\psi(\\ulcorner G\\urcorner)$", "$G$ is provable", "$G = \\psi$"],
    correct: 1,
    explanation: "It yields $G$ provably equivalent to '$\\psi$ holds of my own code'. Taking $\\psi=\\neg\\mathrm{Prov}_T$ gives the Gödel sentence.",
    concepts: ["fixed-point-lemma"],
  }],
  "godel-sentence": [{
    id: "mq-godel-sentence-1", type: "true-false",
    prompt: "The Gödel sentence $G_T$ is essentially the liar paradox ('this sentence is false') written in arithmetic.",
    correct: false,
    explanation: "$G_T$ uses *provability* (representable), not *truth* (undefinable, by Tarski), and asserts its own unprovability — giving incompleteness, not paradox.",
    concepts: ["godel-sentence"], misconceptions: ["liar"],
  }],
  "omega-consistency": [{
    id: "mq-omega-consistency-1", type: "true-false",
    prompt: "ω-consistency is strictly stronger than plain consistency.",
    correct: true,
    explanation: "ω-consistency also forbids proving $\\exists x\\,\\varphi(x)$ while refuting every $\\varphi(0),\\varphi(1),\\dots$. Gödel's original $T\\nvdash\\neg G_T$ used it; Rosser dropped back to plain consistency.",
    concepts: ["omega-consistency"],
  }],
  "rosser-sentence": [{
    id: "mq-rosser-sentence-1", type: "multiple-choice",
    prompt: "Rosser's modified sentence lets the First Incompleteness Theorem assume only…",
    options: ["soundness", "ω-consistency", "plain consistency", "completeness"],
    correct: 2,
    explanation: "Rosser's trick yields both $T\\nvdash R$ and $T\\nvdash\\neg R$ from *plain consistency*, weakening Gödel's ω-consistency hypothesis.",
    concepts: ["rosser-sentence"],
  }],
  "first-incompleteness": [{
    id: "mq-first-incompleteness-1", type: "multiple-choice",
    prompt: "For the standard construction, the *truth* of $G_T$ in $\\mathbb{N}$ requires…",
    options: ["soundness of $T$", "only consistency of $T$", "completeness of $T$", "that $T$ proves $G_T$"],
    correct: 1,
    explanation: "Consistency gives no proof of $G_T$, and the $G_T\\leftrightarrow\\neg\\mathrm{Prov}$ biconditional holds in $\\mathbb{N}$ via the base arithmetic — so $G_T$ is true from consistency alone. Soundness is sufficient but not necessary.",
    concepts: ["first-incompleteness"], misconceptions: ["true-prov"],
  }],
  "con-t": [{
    id: "mq-con-t-1", type: "multiple-choice",
    prompt: "$\\mathrm{Con}(T)$ is the arithmetic sentence…",
    options: ["$T \\vdash 0=1$", "$\\neg\\mathrm{Prov}_T(\\ulcorner 0=1\\urcorner)$ — no proof of $0=1$ exists", "$\\mathbb{N}\\models T$", "$T$ is complete"],
    correct: 1,
    explanation: "$\\mathrm{Con}(T)$ encodes 'there is no $T$-proof of $0=1$' as an arithmetic statement about code-numbers.",
    concepts: ["con-t"], misconceptions: ["con-false"],
  }],
  "second-incompleteness": [{
    id: "mq-second-incompleteness-1", type: "true-false",
    prompt: "If $T$ is consistent, effectively axiomatized, and strong enough, then $T \\nvdash \\mathrm{Con}(T)$ — it cannot prove its own consistency.",
    correct: true,
    explanation: "That is the Second Incompleteness Theorem: consistency is among the truths a consistent strong theory cannot establish about itself.",
    concepts: ["second-incompleteness"],
  }],
};
